* Config/Preamble :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\definecolor{SlateGrey}{HTML}{2E2E2E}
\\definecolor{LightGrey}{HTML}{666666}
\\definecolor{DarkPastelRed}{HTML}{450808}
\\definecolor{PastelRed}{HTML}{8F0D0D}
\\definecolor{GoldenEarth}{HTML}{E7D192}

\\colorlet{name}{black}
\\colorlet{tagline}{PastelRed}
\\colorlet{heading}{DarkPastelRed}
\\colorlet{headingrule}{GoldenEarth}
\\colorlet{subheading}{PastelRed}
\\colorlet{accent}{PastelRed}
\\colorlet{emphasis}{SlateGrey}
\\colorlet{body}{LightGrey}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")
               ("\\cvevent{%s}" . "\\cvevent*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)
        ))
#+END_SRC
#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}
*** Bibliography
# #+LATEX_HEADER: \DeclareNameAlias{sortname}{last-first}
#+LATEX_HEADER: \DeclareNameAlias{sortname}{given-family}
#+LATEX_HEADER: \addbibresource{aidan.bib}
# #+LATEX_HEADER: \usepackage[citestyle=numeric-comp, maxcitenames=1, maxbibnames=4, doi=false, isbn=false, eprint=true, backend=bibtex, hyperref=true, url=false, natbib=true]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=biber, sorting=nyvt, style=authoryear, firstinits]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=natbib, giveninits=true]{biblatex}
#+LATEX_HEADER: \usepackage[style=trad-abbrv,sorting=none,sortcites=true,doi=false,url=false,giveninits=true,hyperref]{biblatex}

** Exporter Settings
#+AUTHOR: Giovanni Crisalfi
#+EXPORT_FILE_NAME: ./curriculum-vitae.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage
* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Giovanni Crisalfi}
\photoR{2.8cm}{propic-ciliegio.jpg}
\tagline{Studente}
#+end_export

** Personal Info :ignore:
#+begin_export latex
\personalinfo{
  \homepage{www.zwitterio.it}
  \email{giovanni.crisalfi@protonmail.com}
  \phone{+39 3331604917}
  \location{Caltagirone, CT}
  \github{gicrisf}
  \twitter{gicrisf}
  \dob{27 Dicembre 1995}
  \driving{Patente B}
}
\makecvheader
#+end_export

* CV Column 1 :ignore:
#+begin_export latex
\begin{paracol}{2}
#+end_export

** Personal Statement English :ignore:noexport:
#+begin_quote
Medicinal chemistry student at Unibo • Into spectroscopy and radicals • Linux citizen • Coding in Rust • Scripting in Python/Lisp • Reading and writing around.
#+end_quote
** Personal Statement Italian :ignore:
#+begin_quote
Studente di CTF appassionato di spettroscopia e simulazioni computazionali.
Sostenitore dell'Open Source, vivo su Linux e scrivo sia codice che prosa su Emacs.
Mi interesso di epistemologia, cinema, fumetti e altre lettere.
#+end_quote

#+latex: \vspace{.1cm}

** Publications :noexport:
#+begin_export latex
\nocite{*}
% \printbibliography[heading=pubtype,title={\printinfo{\faBook}{Books}},type=book]
% \divider
% \printbibliography[heading=pubtype,title={\printinfo{\faFile*[regular]}{Journal Articles}},type=article]
% \divider
\printbibliography[heading=pubtype,title={\printinfo{\faUsers}{Conference Proceedings}},type=inproceedings]
#+end_export

** Progetti
*** Esrafel :ignore:
{{{cvevent(ESRafel, Software for least-squares fitting of ESR/EPR spectra with Monte Carlo methods, Marzo 2020 - Marzo 2022)}}}

- [[https://github.com/gicrisf/esrafel][\faGithub gicrisf/esrafel]]
#+latex: \vspace{.2cm}

{{{cvtag(Sviluppo Desktop)}}}
{{{cvtag(Rust)}}}
{{{cvtag(GTK)}}}
{{{cvtag(Spettroscopia)}}}

*** Zhuia :ignore:
{{{par-div}}}

{{{cvevent(Zhuia, An elegant but still playful theme for Zola, Feb. 2022 - Marzo 2022)}}}

- [[https://github.com/gicrisf/zhuia][\faGithub gicrisf/zhuia]]
#+latex: \vspace{.2cm}

{{{cvtag(Sviluppo Web)}}}
{{{cvtag(Rust)}}}
{{{cvtag(Zola)}}}
# {{{cvtag(Jinja2 (Tera))}}}

*** Gotosi :ignore:noexport:
{{{par-div}}}

{{{cvevent(Gotosi, Isotope oriented periodic table of elements, Feb. 2021 - Maggio 2021)}}}

- [[https://github.com/gicrisf/gotosi-gtk][\faGithub gicrisf/gotosi-gtk]]
#+latex: \vspace{.2cm}

{{{cvtag(Sviluppo Desktop)}}}
{{{cvtag(Vala)}}}
{{{cvtag(GTK)}}}
{{{cvtag(Chimica)}}}

*** Unsplash :ignore:
{{{par-div}}}

{{{cvevent(3D renders, Bio/chem molecular renders for fun and blogging,)}}}

- [[https://unsplash.com/@gicrisf][\faUnsplash @gicrisf]]
#+latex: \vspace{.2cm}

{{{cvtag(VMD)}}}
{{{cvtag(GIMP)}}}
{{{cvtag(Grafica)}}}
{{{cvtag(Chimica)}}}

** Seminari
*** Festival della scienza medica :ignore:

{{{cvevent(Festival della Scienza Medica, Palazzo Re Enzo - piazza Nettuno 1 - Bologna, Anni: 2016 - 2017 - 2018 - 2019)}}}

#+begin_comment
- 19/05/2016 – 22/05/2016: 'Le età della vita'
- 20/04/2017 – 23/04/2017: 'Fra innovazione e tradizione'
- 03/05/2018 – 06/05/2018: 'Il tempo della cura'
- 09/05/2019 – 12/05/2019: 'Intelligenza della salute'
#+end_comment

*** SITOX :ignore:

{{{par-div}}}

{{{cvevent(18° Congresso Nazionale Sitox, Savoia Hotel Regency Via del Pilastro 2 40127 Bologna, 10 Apr. 2018 – 13 Apr. 2018)}}}

*** ChemistryWorld :ignore:

{{{par-div}}}

{{{cvevent(Driving the development of bio-based polymers with molecular simulation, ChemistryWorld Webinar, 13 Apr. 2022)}}}

{{{par-div}}}

{{{cvevent(Accelerating first-in-class and best-in-class programs using a large-scale digital chemistry strategy, ChemistryWorld Webinar, 24 Maggio 2022)}}}

** Newpage :ignore:noexport:
{{{new-page}}}

** Projects (Cont.) :ignore:noexport:

*** Active Learning :ignore:
{{{par-div}}}
# {{{cvevent(Investigating Exploration-Exploitation in Multimodal Dynamical Systems (Academic), University of Bristol, May 2021 - Ongoing, Bristol\, UK)}}}
{{{cvevent(Optimal Control in Multimodal Dynamical Systems as Probabilistic Inference, University of Bristol, May 2021 - Ongoing, Bristol\, UK)}}}

- Developing data-efficient techniques for exploration in multimodal dynamical systems.
- The goal of this project is to explore a single dynamics mode that is known to be operatable whilst avoiding other modes.

{{{cvtag(Variational inference)}}}
{{{cvtag(Gaussian processes)}}}
{{{cvtag(Optimal control)}}}

** A day of my life :noexport:
# #+begin_export latex
# % \medskip

# % \cvsection{A Day of My Life}

# % % Adapted from @Jake's answer from http://tex.stackexchange.com/a/82729/226
# % % \wheelchart{outer radius}{inner radius}{
# % % comma-separated list of value/text width/color/detail}
# % \wheelchart{1.5cm}{0.5cm}{%
# %   6/8em/accent!30/{Sleep,\\beautiful sleep},
# %   3/8em/accent!40/Hopeful novelist by night,
# %   8/8em/accent!60/Daytime job,
# %   2/10em/accent/Sports and relaxation,
# %   5/6em/accent!20/Spending time with family
# % }

# % % use ONLY \newpage if you want to force a page break for
# % % ONLY the current column
# % \newpage
# #+end_export

** Newpage :ignore:noexport:
{{{new-page}}}

** Volunteering :noexport:
*** FARSCOPE Course Rep :ignore:
{{{cvevent(Cohort Representative, FARSCOPE CDT, Sept 2018 - Ongoing, Bristol\, UK)}}}
# - I represent myself and fellow CDT students in management meetings where I communicate ideas and information between students and management.
- Represent myself and my CDT peers in management meetings.
- Communicate information between students and management.

{{{cvtag(Communication)}}}
{{{cvtag(Interpersonal Skills)}}}

{{{par-div}}}

*** Code Club :ignore:
{{{cvevent(Club Leader, Code Club, Dec 2017 - April 2018, Junction 3 Library\, Bristol \, UK)}}}

# - I collaborated with [[https://codeclub.org/en/][Code Club]] and Bristol Libraries to set up and run a Code Club for young people aged 9-13.
# - Demonstrating my abi involved organising,  planning lessons and teaching
- Set up (and then ran) a [[https://codeclub.org/en/][Code Club]] for children aged 9-13.
- Led the organisation, planning and teaching of weekly lessons.
- Planned lessons to engage children by making coding fun.
- Extremely rewarding and reinforced my love for teaching.
# - @ Junction 3 Library in Easton, Bristol.

{{{cvtag(Leadership)}}}
{{{cvtag(Teaching)}}}
{{{cvtag(Communication)}}}
{{{cvtag(Active listening)}}}

*** Drivetrain :ignore:noexport:
{{{par-div}}}

{{{cvevent(Technical Lead (Drivetrain), Formula Student, Jan 2015 - Jan 2016, Bristol\, UK)}}}

Each year, as part of Formula Student, students design, build and race a single seat race car.
- Finished 2nd in the National Class 2 competition in 2013/2014, I was then selected as the Drivetrain lead.
- This role improved my communication skills as I was leading weekly presentations.
- I developed my leadership skills through setting realistic objectives, effectively allocating work to the appropriate team members and monitoring outcomes.

{{{cvtag(Teamwork)}}}
{{{cvtag(Leadership)}}}
{{{cvtag(Time Management)}}}

*** Snowboard Captain :ignore:noexport:
{{{par-div}}}

{{{cvevent(Snowboard Captain, University of Bristol Snowsports Club, Jan 2014 - Sept 2015, Bristol\, UK)}}}

- Organised multiple weekly training sessions, demonstrating my ability to plan and run events smoothly.
- Negotiated competitive prices for a growing member base within an inherently expensive sport.
- Responsible for aiding the smooth running of the club and helping to organise the annual university ski trip, with circa 1500 participants, working under pressure to manage people in high stress situations.
- Awarded the ‘Team of the Year’ award and full colours for my performances and contributions to the sport.

{{{cvtag(Teamwork)}}}
{{{cvtag(Leadership)}}}
{{{cvtag(Time Management)}}}

** Invited Talks :noexport:
*** Geometry Talk :ignore:
{{{cvevent(Synergising Bayesian Inference and Probabilistic Geometries for Robotic Control, Cognitive Systems - Technical University of Denmark (DTU), 18 March 2021, Zoom)}}}
# - Presented a method for controlling multimodal dynamical systems synergising Bayesian inference and probabilistic geometries.
- Presented a method synergising Bayesian inference and probabilistic geometries to control multimodal dynamical systems.

{{{cvtag(Communication)}}}
{{{cvtag(Probabilistic geometries)}}}
{{{cvtag(Gaussian processes)}}}

* CV Column 2 :ignore:
# Switch to the right column - will automatically move to the next page.
#+begin_export latex
\switchcolumn
#+end_export

** Competenze
{{{cvtag(Analisi farmaceutica)}}}
{{{cvtag(Grafica)}}}
{{{cvtag(Data viz)}}}

#+latex: \vspace{-.1cm}

{{{cvtag(Rust)}}}
{{{cvtag(Vala)}}}
{{{cvtag(Python)}}}
{{{cvtag(JavaScript)}}}

#+latex: \vspace{.1cm}

{{{cvtag(Lisp)}}}
{{{cvtag(GTK)}}}
{{{cvtag(HTML/CSS)}}}
{{{cvtag(Git)}}}

** Esperienze
{{{cvevent(Tirocinio in Farmacia Ospedaliera, Ospedale Gravina di Caltagirone, Ottobre 2020 - Luglio 2021)}}}

{{{par-div}}}

{{{cvevent(Tirocinio per tesi sperimentale, Dipartimento di Chimica "Giacomo Ciamician" - Unibo, Ottobre 2019 - Maggio 2020)}}}

** Istruzione
# {{{cvevent(PhD\ in Bayesian Machine Learning for Robotic Control, University of Bristol, Sept 2018 - Ongoing,)}}}
# - \faBook Probabilistic Inference for Learning and Control in Multimodal Dynamical Systems

# {{{divider}}}

# {{{cvevent(Gaussian Process and Uncertainty Quantification Summer School (GPSS), University of Sheffield, Sept 2019 - Sept 2019,)}}}

# {{{divider}}}

# {{{cvevent(Machine Learning Summer School Moscow (MLSS), Skoltech, Aug 2019 - Sept 2019,)}}}

# {{{cvevent(M.Res.\ in Robotics \& Autonomous Systems, University of Bristol | First Class Honours, Sept 2017 -- Sept 2018,)}}}
# {{{cvevent(a \footnote{Not official - will be awarded if Ph.D. is not completed.} M.Res.\ in Robotics \& Autonomous Systems,University of Bristol,Sept 2017 -- Sept 2018,)}}}
#+BEGIN_EXPORT latex
% \cvevent{\footnote{Awarded if PhD is not completed.} MRes in Robotics \& Autonomous Systems}{University of Bristol | First Class Honours}{Sept 2017 -- Sept 2018}{}
#+END_EXPORT
# - First Class Honours
# - \faBook [[https://www.aidanscannell.com/project/uncertain-agentspeak/][Extending BDI Agents to Model and Reason with Uncertainty]]

{{{cvevent(Summer School in Pharmaceutical Analysis, Campus di Rimini - Palazzo Ruffi-Briolini, 18 Sett. 2017 – 20 Sett. 2017)}}}
- Advanced Analytical Methodologies for Adsorption, Distribution, Metabolism, Excretion and Toxicity (ADMET) Studies

{{{divider}}}

{{{cvevent(Magistrale a ciclo unico in Chimica e Tecnologia Farmaceutiche, Dipartimento di Farmacia e Biotecnologie FABIT | Università di Bologna, Sett. 2014 -- In corso)}}}
# - First Class Honours \\
# - Graduated in top 10% of cohort

{{{divider}}}

{{{cvevent(Diploma, Liceo Scientifico E. Majorana | Caltagirone, Sett. 2009 -- Giugno 2014)}}}

** Newpage :ignore:noexport:
#+BEGIN_EXPORT latex
\newpage
#+END_EXPORT

** My Life Philosophy :noexport:
#+begin_export latex
% \begin{quote}
% ``Something smart or heartfelt, preferably in one sentence.''
% \end{quote}
#+end_export

# ** Most Proud Of :ignore:
# #+begin_export latex
# \cvsection{Most Proud of}
# #+end_export

# #+begin_export latex
# \cvachievement{\faTrophy}{Code Club Leader}{Collaborated with Code Club and Bristol Libraries to set up and run a Code Club for 9-13 year olds.}
# #+end_export

# #+begin_export latex
# \divider

# \cvachievement{\faHeartbeat}{British University Snowboard Slalom Champion}{Won all national British university slalom competitions in 2017-2018.}
# #+end_export

** Achievements :noexport:
{{{cvachievement(\faTrophy, Full Sporting Colours, Awarded full colours for outstanding achievements in snowboarding. Multiple gold medals in British University Snowboard Championships.)}}}

{{{divider}}}

{{{cvachievement(\faCertificate, Starting To Teach, Established myself as a confident\, enthusiastic and effective teacher who is able to engage\, encourage and develop students' learning.)}}}

{{{divider}}}

{{{cvachievement(\faTrophy,Bristol Plus Award, For undertaking a wide range of tasks to further enhance student skills - only 700 out of 23\,000 achieved this award per annum.)}}}

{{{divider}}}

{{{cvachievement(\faCertificate, Mary Jones Prize for Mathematics, For outstanding achievements in A Level mathematics @ Ripon Grammar School)}}}

{{{divider}}}

{{{cvachievement(\faTrophy, The Duke of Edinburgh's Award, Bronze/Silver/Gold)}}}

** Lingue :ignore:
#+begin_export latex
\cvsection{Lingue}

\cvskill{Italiano}{5}
\divider

\cvskill{Inglese}{4}
\divider

\cvskill{Francese}{1}

% %% Yeah I didn't spend too much time making all the
% %% spacing consistent... sorry. Use \smallskip, \medskip,
% %% \bigskip, \vpsace etc to make ajustments.
% \medskip
#+end_export

# \newpage
** References :noexport:
#+begin_export latex
% \cvref{name}{email}{mailing address}
\cvref{Prof.\ Arthur Richards}{University of Bristol}{arthur.richards@bristol.ac.uk}
% {Address Line 1\\Address line 2}
\divider
\cvref{Dr.\ Carl Henrik Ek}{University of Cambridge}{che29@cam.ac.uk}
% {Address Line 1\\Address line 2}
#+end_export
** GDPR :ignore:noexport:

{{{divider}}}

#+latex: {\footnotesize
Autorizzo il trattamento dei miei dati personali presenti nel CV ai sensi dell’art. 13 d. lgs. 30 giugno 2003 n. 196 - “Codice in materia di protezione dei dati personali” e dell’art. 13 GDPR 679/16 - “Regolamento europeo sulla protezione dei dati personali”.
#+latex: }

* Back Matter :ignore:
#+begin_export latex
\end{paracol}
\end{document}
#+end_export



